export declare function setPathSeparator(separator: string): void;
export declare function join(...paths: string[]): string;
export declare function basename(path: string): string;
export declare function normalize(path: string): string;
export declare function extname(path: string): string;
export declare function toWinPath(path: string): string;
export declare function toUnixPath(path: string): string;
export declare function dirname(path: string): string;
export declare function isPathInside(containingPath: string, path: string): boolean;
export declare function isRelative(path: string): boolean;
export declare function pathDepth(path: string): number;
